# Generated by Django 6.0.2 on 2026-03-31 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=30)),
                ('descripcion_tienda', models.TextField(blank=True, max_length=1000, null=True)),
                ('avatar_tienda', models.ImageField(default='tienda.png', upload_to='tiendas/')),
                ('estado_tienda', models.CharField(choices=[('abierta', 'Abierta'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='abierta', max_length=7)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_tiendas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30)),
                ('descripcion_producto', models.TextField(blank=True, max_length=1000, null=True)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_producto', models.IntegerField()),
                ('estado_producto', models.CharField(choices=[('disponible', 'Disponible'), ('pausado', 'Pausado'), ('retirado', 'Retirado')], default='disponible', max_length=10)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.tienda')),
            ],
        ),
    ]
