# Generated by Django 6.0.2 on 2026-05-11 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_direcciontienda_direccionusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='direcciontienda',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccionusuario',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_producto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_producto',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('pausado', 'Pausado'), ('retirado', 'Retirado')], default='disponible', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_producto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='descripcion_tienda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='estado_tienda',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='abierta', max_length=15),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre_tienda',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_tiendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_usuario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.producto')),
            ],
        ),
    ]
