# Generated by Django 6.0.2 on 2026-05-19 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_detallepedido_precio_unitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado - Preparando envío'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(related_name='pedidos_incluidos', through='core.DetallePedido', to='core.producto'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='banner_tienda',
            field=models.ImageField(blank=True, default='banner_default.jpg', null=True, upload_to='tiendas/banners/'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='url_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='url_twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.categoria'),
        ),
    ]
