# Generated by Django 6.0.2 on 2026-05-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_pedido_estado_pedido_pedido_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='cantidad',
            new_name='cantidad_producto',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='precio_unitario',
            new_name='precio_unitario_producto',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='subtotal',
            new_name='subtotal_producto',
        ),
        migrations.RenameField(
            model_name='direcciontienda',
            old_name='direccion',
            new_name='direccion_tienda',
        ),
        migrations.RenameField(
            model_name='direccionusuario',
            old_name='direccion',
            new_name='direccion_usuario',
        ),
        migrations.RenameField(
            model_name='imagenproducto',
            old_name='imagen',
            new_name='imagen_producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pedido',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='banner_tienda',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='url_instagram',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='url_twitter',
        ),
        migrations.AlterUniqueTogether(
            name='direcciontienda',
            unique_together={('direccion_tienda', 'tienda')},
        ),
        migrations.AlterUniqueTogether(
            name='direccionusuario',
            unique_together={('direccion_usuario', 'usuario')},
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
