# Generated by Django 6.0.2 on 2026-05-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_valoracion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detallepedido',
            name='unique_pedido_producto',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
