# Generated by Django 6.0.2 on 2026-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carrito_pedido_detallepedido_carritoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='banner_tienda',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/banners/'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='avatar_tienda',
            field=models.ImageField(default='tienda.png', upload_to='tiendas/avatars/'),
        ),
    ]
