# Generated by Django 6.0.2 on 2026-05-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tienda_banner_tienda_alter_tienda_avatar_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='avatar_tienda',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/avatars/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/avatars/'),
        ),
    ]
